import Head from "next/head";
import { Inter } from "next/font/google";
import ListArticle from "@/components/list-article";
import { useEffect } from "react";
import { FirebaseHelper } from "@/lib/firebase-helpers";


const inter = Inter({ subsets: ["latin"] });

export async function getStaticProps() {

  return {
    props: {
    }, // will be passed to the page component as props
  };
}

export default function Home(props: any) {
  useEffect(() => {
    FirebaseHelper.syncMyProfile()
  }, [])
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="posts-inner list-layout">
        <ListArticle />
        <ListArticle />
        <ListArticle />
        <ListArticle />

        <ListArticle />
        <ListArticle />
        <ListArticle />
      </div>
    </>
  );
}
